# Generated by Django 4.2.4 on 2023-08-14 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='event', max_length=100)),
                ('uid', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('tagline', models.CharField(max_length=100)),
                ('schedule', models.DateTimeField()),
                ('description', models.TextField()),
                ('files', models.JSONField()),
                ('moderator', models.IntegerField()),
                ('category', models.CharField(max_length=50)),
                ('sub_category', models.CharField(max_length=50)),
                ('rigor_rank', models.IntegerField()),
                ('attendees', models.JSONField()),
            ],
        ),
    ]
